In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Users\KIIT\Downloads\archive\IRIS.csv")
df.head(3)

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa

In [3]:
df.shape

(150, 5)

In [4]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [5]:
X = df.drop(['species'],axis=1)
print(X)

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]


In [6]:
from sklearn.preprocessing import LabelEncoder

In [8]:
Y = df['species']

In [9]:
lb = LabelEncoder()
df['species'] = lb.fit_transform(Y)

In [10]:
Y = df['species']
Y.unique()

array([0, 1, 2])

In [11]:
X.shape, Y.shape


((150, 4), (150,))

In [12]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X,Y,test_size=0.2,random_state=20)

In [13]:
x_train.shape,y_train.shape

((120, 4), (120,))

In [14]:
x_test.shape

(30, 4)

In [15]:
from sklearn.linear_model import LogisticRegression

In [16]:
lr_model = LogisticRegression()
lr_model = lr_model.fit(x_train,y_train)

In [17]:
lr_predict = lr_model.predict(x_test)
lr_predict

array([0, 1, 1, 2, 1, 1, 2, 0, 2, 0, 2, 1, 1, 0, 0, 2, 0, 1, 2, 1, 1, 2,
       2, 0, 1, 1, 1, 0, 2, 1])

In [18]:
from sklearn.metrics import accuracy_score, confusion_matrix, mean_squared_error

In [20]:
accuracy = lr_model.score(x_train,y_train)
print(accuracy)

0.9666666666666667


In [22]:
accuracy_predicted = lr_model.score(x_test,y_test)
print(accuracy_predicted)

0.9333333333333333


In [23]:
print(confusion_matrix(y_test,lr_predict))

[[ 8  0  0]
 [ 0 11  0]
 [ 0  2  9]]
